export const HERO_DEFS = {
  elliot: {
    name: 'Elliot',
    abilityKey: 'Q',
    abilityName: 'BLINK',
    abilityMaxCd: 6,
    abilityColor: '#80c8ff',
    weaponType: 'longClub',
    maxHp: 100,
    atkRange: 56,
    baseAtkDmg: 32,
    baseAtkRate: 0.55,
    fallbackRenderer: 'elliot',
    palette: {
      shirt: '#d94a78', acc1: '#f5d04a', acc2: '#40c8c0', acc3: '#f8f0d0',
      shorts: '#8a6840', skin: '#e8b888',
      hat: '#d4b880', hatTop: '#bfa270', hatBand: '#5a3a1a',
    },
  },
  dick: {
    name: 'Dick',
    abilityKey: 'W',
    abilityName: 'RAGE',
    abilityMaxCd: 12,
    abilityColor: '#ff6040',
    weaponType: 'dualClubs',
    maxHp: 120,
    atkRange: 36,
    baseAtkDmg: 24,
    baseAtkRate: 0.34,
    fallbackRenderer: 'dick',
    palette: {
      skin: '#d8a878', skinShade: '#a8784a', skinDark: '#7a5030',
      cap: '#2a1a0a', capTop: '#3a2515', capBtn: '#c53030',
    },
  },
  habib: {
    name: 'Habib',
    abilityKey: 'E',
    abilityName: 'CHAIN LTG',
    abilityMaxCd: 8,
    abilityColor: '#c8a0ff',
    weaponType: 'thrownClub',
    maxHp: 100,
    atkRange: 220,
    baseAtkDmg: 36,
    baseAtkRate: 0.9,
    fallbackRenderer: 'habib',
    palette: {
      shirt: '#ece8dc', shirtShade: '#b8b0a0',
      shorts: '#c53030', shortsShade: '#8a1e1e',
      skin: '#d4a878', hair: '#3a2a15',
    },
  },
};
