export const DEFAULT_PICKUP_R = 60;
export const UNIT_RENDER_SCALE = 1.35; // Controls the visual size of heroes

export const HERO_DEFS = {
  eliott: {
    name: 'Eliott',
    abilityKey: '1',
    abilityName: 'GROUP BLINK',
    abilityId: 'group_blink',
    abilityDescription: 'Teleports Eliott up to 240px toward cursor. Allies within 120px are pulled to destination.',
    abilityMaxCd: 9,
    abilityColor: '#80c8ff',
    startingWeapon: 'frozen_cutlet',
    weaponPool: ['frozen_cutlet', 'pickle_jar', 'bottle_cap_shuriken', 'fence_wire_bow', 'bike_spoke_slingshot', 'car_antenna'],
    maxHp: 100,
    fallbackRenderer: 'eliott',
    pickupR: DEFAULT_PICKUP_R,
    palette: {
      shirt: '#d94a78', acc1: '#f5d04a', acc2: '#40c8c0', acc3: '#f8f0d0',
      shorts: '#8a6840', skin: '#e8b888',
      hat: '#d4b880', hatTop: '#bfa270', hatBand: '#5a3a1a',
    },
  },
  dick: {
    name: 'Dick',
    abilityKey: '2',
    abilityName: 'BOOMERANG',
    abilityId: 'boomerang',
    abilityDescription: 'Throws hockey club in an oval arc at the heaviest enemy (300px). 40 dmg outbound, 25 dmg return. Dick is unarmed during flight.',
    abilityMaxCd: 10,
    abilityColor: '#ff6040',
    startingWeapon: 'car_antenna',
    weaponPool: ['car_antenna', 'bus_stop_pole', 'toilet_lid', 'chain_with_padlock', 'contraceptive_catapult', 'richards_megaphone'],
    maxHp: 120,
    fallbackRenderer: 'dick',
    pickupR: DEFAULT_PICKUP_R,
    palette: {
      skin: '#d8a878', skinShade: '#a8784a', skinDark: '#7a5030',
      cap: '#2a1a0a', capTop: '#3a2515', capBtn: '#c53030',
    },
  },
  habib: {
    name: 'Habib',
    abilityKey: '3',
    abilityName: 'BLOCKADE',
    abilityId: 'backdoor_blockade',
    abilityDescription: 'Active Survival Shield (A.S.S) exoshell enablement. All heroes within 150px take 50% reduced damage for 6s.',
    abilityMaxCd: 14,
    abilityColor: '#c8a0ff',
    startingWeapon: 'extension_cord',
    weaponPool: ['extension_cord', 'shower_hose', 'bike_spoke_slingshot', 'bed_spring_arbalest', 'courtyard_railgun', 'chain_with_padlock'],
    maxHp: 100,
    fallbackRenderer: 'habib',
    pickupR: DEFAULT_PICKUP_R,
    palette: {
      shirt: '#ece8dc', shirtShade: '#b8b0a0',
      shorts: '#c53030', shortsShade: '#8a1e1e',
      skin: '#d4a878', hair: '#3a2a15',
    },
  },
};
