export const HERO_DEFS = {
  eliott: {
    name: 'Eliott',
    abilityKey: '1',
    abilityName: 'GROUP BLINK',
    abilityMaxCd: 9,
    abilityColor: '#80c8ff',
    startingWeapon: 'short_hockey_club',
    maxHp: 100,
    fallbackRenderer: 'eliott',
    palette: {
      shirt: '#d94a78', acc1: '#f5d04a', acc2: '#40c8c0', acc3: '#f8f0d0',
      shorts: '#8a6840', skin: '#e8b888',
      hat: '#d4b880', hatTop: '#bfa270', hatBand: '#5a3a1a',
    },
  },
  dick: {
    name: 'Dick',
    abilityKey: '2',
    abilityName: 'BOOMERANG',
    abilityMaxCd: 10,
    abilityColor: '#ff6040',
    startingWeapon: 'hockey_club',
    maxHp: 120,
    fallbackRenderer: 'dick',
    palette: {
      skin: '#d8a878', skinShade: '#a8784a', skinDark: '#7a5030',
      cap: '#2a1a0a', capTop: '#3a2515', capBtn: '#c53030',
    },
  },
  habib: {
    name: 'Habib',
    abilityKey: '3',
    abilityName: 'BLOCKADE',
    abilityMaxCd: 14,
    abilityColor: '#c8a0ff',
    startingWeapon: 'hockey_club',
    maxHp: 100,
    fallbackRenderer: 'habib',
    palette: {
      shirt: '#ece8dc', shirtShade: '#b8b0a0',
      shorts: '#c53030', shortsShade: '#8a1e1e',
      skin: '#d4a878', hair: '#3a2a15',
    },
  },
};
