// ── Weapon definitions ────────────────────────────────────────────────────────
// Each entry fully describes a weapon's stats, behaviour, audio, and sprite.
// Heroes reference a key here via startingWeapon and weaponPool.
//
// type:
//   melee   — close-range swing; hits the single closest target in arc
//   cleave  — melee with arc hit on all enemies in a cone
//   thrown  — homing projectile that (optionally) returns to the thrower
//   ranged  — straight-line projectile(s), no return
//
// rarity: Common | Rare | Epic | Legendary — used by WeaponLevelUpScene card UI
// levels: 5-entry array of per-level stat overrides (added in commit 2)

export const WEAPON_DEFS = {

  // ── Melee ──────────────────────────────────────────────────────────────────

  car_antenna: {
    displayName:   'Car Antenna',
    type:          'melee',
    behavior:      'multiSlash',
    rarity:        'Common',
    atkRange:      150,
    atkDmg:        40,
    atkRate:       0.55,
    knockback:     40,
    slash:         { count: 3, stagger: 0.06 },
    swingArc:      1.5,
    swingOffset:   1.0,
    sfxAttack:     'weapon.attack.default',
    sfxFallback:   'weapon.attack.default',
    sprite:        'car_antenna',
    lootDuration:  null,
    levels: [
      { atkDmg: 40, atkRate: 0.55 },
      { atkDmg: 60, atkRate: 0.52 },
      { atkDmg: 80, atkRate: 0.49 },
      { atkDmg: 100, atkRate: 0.46 },
      { atkDmg: 120, atkRate: 0.43 },
    ],
  },

  toilet_lid: {
    displayName:   'Toilet Lid',
    type:          'melee',
    behavior:      'bounce',
    rarity:        'Rare',
    cleave:        true,
    cleaveArc:     55,
    atkRange:      45,
    atkDmg:        95,
    atkRate:       1.3,
    knockback:     160,
    bounce:        { maxBounces: 3, pierce: false, lifetime: 5.0, offBounds: false, gravity: 800 },
    sfxAttack:     'weapon.attack.default',
    sfxFallback:   'weapon.attack.default',
    sprite:        'toilet_lid',
    lootDuration:  null,
    levels: [
      { atkDmg: 95, atkRate: 1.30 },
      { atkDmg: 142.5, atkRate: 1.23 },
      { atkDmg: 190, atkRate: 1.16 },
      { atkDmg: 237.5, atkRate: 1.09 },
      { atkDmg: 285, atkRate: 1.02 },
    ],
  },

  bus_stop_pole: {
    displayName:   'Bus Stop Pole',
    type:          'melee',
    behavior:      'arcDown',
    rarity:        'Epic',
    atkRange:      80,
    atkDmg:        150,
    atkRate:       2.0,
    knockback:     200,
    arc:           { upSpeed: 400, drift: 100, gravity: 800, pierce: true },
    swingArc:      2.4,
    swingOffset:   1.2,
    sfxAttack:     'weapon.attack.default',
    sfxFallback:   'weapon.attack.default',
    sprite:        'bus_stop_pole',
    lootDuration:  null,
    levels: [
      { atkDmg: 150, atkRate: 2.0 },
      { atkDmg: 225, atkRate: 1.9 },
      { atkDmg: 300, atkRate: 1.8 },
      { atkDmg: 375, atkRate: 1.7 },
      { atkDmg: 450, atkRate: 1.6 },
    ],
  },


  shower_hose: {
    displayName:   'Shower Hose',
    type:          'melee',
    behavior:      'whip',
    rarity:        'Rare',
    cleave:        true,
    cleaveArc:     45,
    atkRange:      75,
    atkDmg:        80,
    atkRate:       1.2,
    knockback:     70,
    whip:          { shape: 'lash', length: 100, halfHeight: 22, sides: 1, pattern: 'wave', amplitude: 28, waves: 1, color: '#ffffff' },
    sfxAttack:     'weapon.whip.crack',
    sfxFallback:   'weapon.attack.default',
    sprite:        'shower_hose',
    lootDuration:  null,
    levels: [
      { atkDmg: 80, atkRate: 1.20 },
      { atkDmg: 120, atkRate: 1.14 },
      { atkDmg: 160, atkRate: 1.08 },
      { atkDmg: 200, atkRate: 1.02 },
      { atkDmg: 240, atkRate: 0.96 },
    ],
  },

  chain_with_padlock: {
    displayName:   'Doggo Chain',
    type:          'melee',
    behavior:      'orbit',
    rarity:        'Epic',
    cleave:        true,
    cleaveArc:     60,
    atkRange:      65,
    atkDmg:        110,
    atkRate:       1.6,
    knockback:     180,
    orbit:         { count: 2, radius: 64, angularSpeed: 2.6, duration: 2.0, tickInterval: 0.25 },
    sfxAttack:     'weapon.attack.default',
    sfxFallback:   'weapon.attack.default',
    sprite:        'chain_with_padlock',
    lootDuration:  null,
    levels: [
      { atkDmg: 110, atkRate: 1.60 },
      { atkDmg: 165, atkRate: 1.52 },
      { atkDmg: 220, atkRate: 1.44 },
      { atkDmg: 275, atkRate: 1.36 },
      { atkDmg: 330, atkRate: 1.28 },
    ],
  },

  extension_cord: {
    displayName:   'Extension Cord',
    type:          'melee',
    behavior:      'whip',
    rarity:        'Common',
    cleave:        true,
    cleaveArc:     50,
    atkRange:      70,
    atkDmg:        70,
    atkRate:       1.0,
    knockback:     60,
    whip:          { shape: 'lash', length: 110, halfHeight: 18, sides: 1, pattern: 'zigzag', amplitude: 22, waves: 3, color: '#ffe04a' },
    sfxAttack:     'weapon.whip.crack',
    sfxFallback:   'weapon.attack.default',
    sprite:        'extension_cord',
    lootDuration:  null,
    levels: [
      { atkDmg: 70, atkRate: 1.00 },
      { atkDmg: 105, atkRate: 0.95 },
      { atkDmg: 140, atkRate: 0.90 },
      { atkDmg: 175, atkRate: 0.85 },
      { atkDmg: 210, atkRate: 0.80 },
    ],
  },

  richards_megaphone: {
    displayName:   'Megaphone',
    type:          'melee',
    behavior:      'aura',
    rarity:        'Epic',
    atkRange:      100,
    atkDmg:        15,
    atkRate:       1.0,
    knockback:     20,
    aura:          { radius: 100, tickInterval: 0.5, knockback: 20 },
    sfxAttack:     'weapon.attack.default',
    sfxFallback:   'weapon.attack.default',
    sprite:        'richards_megaphone',
    lootDuration:  null,
    levels: [
      { atkDmg: 15, auraRadius: 100 },
      { atkDmg: 20, auraRadius: 110 },
      { atkDmg: 25, auraRadius: 120 },
      { atkDmg: 30, auraRadius: 130 },
      { atkDmg: 35, auraRadius: 140 },
    ],
  },

  // ── Thrown ─────────────────────────────────────────────────────────────────

  frozen_cutlet: {
    displayName:       'Frozen Cutlet',
    type:              'thrown',
    behavior:          'bounce',
    rarity:            'Common',
    atkRange:          220,
    atkDmg:            40,
    atkRate:           0.8,
    returns:           false,
    piercing:          false,
    bounce:            { maxBounces: 4, pierce: true, lifetime: 3.0, offBounds: true },
    projectileSpeed:   450,
    projectileMaxRange:240,
    sfxThrow:          'shoot',
    sfxImpact:         'hit',
    sfxFallbackThrow:  'shoot',
    sfxFallbackImpact: 'hit',
    sprite:            'frozen_cutlet',
    lootDuration:      null,
    maxProjectiles:    4,
    levels: [
      { atkDmg: 40, atkRate: 0.80, maxProjectiles: 4 },
      { atkDmg: 60, atkRate: 0.76, maxProjectiles: 5 },
      { atkDmg: 80, atkRate: 0.72, maxProjectiles: 6 },
      { atkDmg: 100, atkRate: 0.68, maxProjectiles: 7 },
      { atkDmg: 120, atkRate: 0.64, maxProjectiles: 8 },
    ],
  },

  pickle_jar: {
    displayName:       'Pickle Jar',
    type:              'thrown',
    behavior:          'groundZone',
    rarity:            'Epic',
    atkRange:          200,
    atkDmg:            105,
    atkRate:           1.5,
    returns:           false,
    piercing:          false,
    aoeRadius:         40,
    zone:              { radius: 48, duration: 3.0, tickInterval: 0.4 },
    projectileSpeed:   400,
    projectileMaxRange:220,
    sfxThrow:          'shoot',
    sfxImpact:         'hit',
    sfxFallbackThrow:  'shoot',
    sfxFallbackImpact: 'hit',
    sprite:            'pickle_jar',
    lootDuration:      null,
    maxProjectiles:    2,
    levels: [
      { atkDmg: 105, atkRate: 1.50, maxProjectiles: 2 },
      { atkDmg: 157.5, atkRate: 1.42, maxProjectiles: 2 },
      { atkDmg: 210, atkRate: 1.34, maxProjectiles: 3 },
      { atkDmg: 262.5, atkRate: 1.26, maxProjectiles: 3 },
      { atkDmg: 315, atkRate: 1.18, aoeRadius: 50, maxProjectiles: 4 },
    ],
  },

  bottle_cap_shuriken: {
    displayName:       'Cap Shuriken',
    type:              'thrown',
    behavior:          'boomerang',
    rarity:            'Common',
    atkRange:          260,
    atkDmg:            25,
    atkRate:           0.35,
    returns:           true,
    piercing:          true,
    projectileSpeed:   600,
    projectileMaxRange:280,
    sfxThrow:          'shoot',
    sfxImpact:         'hit',
    sfxFallbackThrow:  'shoot',
    sfxFallbackImpact: 'hit',
    sprite:            'bottle_cap_shuriken',
    lootDuration:      null,
    maxProjectiles:    3,
    levels: [
      { atkDmg: 25, atkRate: 0.35, maxProjectiles: 3 },
      { atkDmg: 37.5, atkRate: 0.33, maxProjectiles: 4 },
      { atkDmg: 50, atkRate: 0.31, maxProjectiles: 5 },
      { atkDmg: 62.5, atkRate: 0.29, maxProjectiles: 6 },
      { atkDmg: 75, atkRate: 0.27, maxProjectiles: 7 },
    ],
  },

  // ── Ranged ─────────────────────────────────────────────────────────────────

  bed_spring_arbalest: {
    displayName:       'Spring Arbalest',
    type:              'ranged',
    behavior:          'bolt',
    targeting:         'random',
    rarity:            'Epic',
    atkRange:          420,
    atkDmg:            110,
    atkRate:           2.0,
    bulletCount:       1,
    spread:            0,
    projectileSpeed:   750,
    sfxFire:           'shoot',
    sfxFallback:       'shoot',
    sprite:            'bed_spring_arbalest',
    projectileSprite:  'spring_bolt',
    lootDuration:      null,
    maxProjectiles:    4,
    levels: [
      { atkDmg: 110, atkRate: 2.0, maxProjectiles: 4 },
      { atkDmg: 165, atkRate: 1.9, maxProjectiles: 5 },
      { atkDmg: 220, atkRate: 1.8, maxProjectiles: 6 },
      { atkDmg: 275, atkRate: 1.7, maxProjectiles: 7 },
      { atkDmg: 330, atkRate: 1.6, maxProjectiles: 8 },
    ],
  },

  bike_spoke_slingshot: {
    displayName:       'Spoke Slingshot',
    type:              'ranged',
    behavior:          'bolt',
    targeting:         'nearest',
    rarity:            'Common',
    atkRange:          350,
    atkDmg:            57,
    atkRate:           0.9,
    bulletCount:       1,
    spread:            0.05,
    projectileSpeed:   600,
    sfxFire:           'shoot',
    sfxFallback:       'shoot',
    sprite:            'bike_spoke_slingshot',
    projectileSprite:  'spoke_ball',
    lootDuration:      null,
    maxProjectiles:    5,
    levels: [
      { atkDmg: 57, atkRate: 0.90, maxProjectiles: 5 },
      { atkDmg: 85.5, atkRate: 0.85, maxProjectiles: 6 },
      { atkDmg: 114, atkRate: 0.80, maxProjectiles: 7 },
      { atkDmg: 142.5, atkRate: 0.75, maxProjectiles: 8 },
      { atkDmg: 171, atkRate: 0.70, maxProjectiles: 9 },
    ],
  },

  courtyard_railgun: {
    displayName:       'Railgun',
    type:              'ranged',
    behavior:          'chargeBeam',
    rarity:            'Legendary',
    atkRange:          500,
    atkDmg:            130,
    atkRate:           2.0,
    beam:              { chargeTime: 1.0, length: 600, halfWidth: 16 },
    bulletCount:       1,
    spread:            0,
    projectileSpeed:   1200,
    sfxFire:           'shoot',
    sfxFallback:       'shoot',
    sprite:            'courtyard_railgun',
    lootDuration:      null,
    levels: [
      { atkDmg: 130, atkRate: 2.0 },
      { atkDmg: 195, atkRate: 1.9 },
      { atkDmg: 260, atkRate: 1.8 },
      { atkDmg: 325, atkRate: 1.7 },
      { atkDmg: 390, atkRate: 1.6 },
    ],
  },

  contraceptive_catapult: {
    displayName:       'Catapult',
    type:              'ranged',
    behavior:          'lobExplode',
    rarity:            'Rare',
    atkRange:          380,
    atkDmg:            75,
    atkRate:           1.1,
    bulletCount:       1,
    spread:            0.1,
    projectileSpeed:   500,
    returns:           false,
    piercing:          false,
    aoeRadius:         70,
    projectileMaxRange:400,
    sfxThrow:          'shoot',
    sfxImpact:         'explosion',
    sfxFire:           'shoot',
    sfxFallback:       'shoot',
    sprite:            'contraceptive_catapult',
    projectileSprite:  'catapult_pouch',
    lootDuration:      null,
    maxProjectiles:    3,
    levels: [
      { atkDmg: 75, atkRate: 1.10, maxProjectiles: 3 },
      { atkDmg: 112.5, atkRate: 1.04, maxProjectiles: 4 },
      { atkDmg: 150, atkRate: 0.98, maxProjectiles: 5 },
      { atkDmg: 187.5, atkRate: 0.92, maxProjectiles: 6 },
      { atkDmg: 225, atkRate: 0.86, maxProjectiles: 7 },
    ],
  },

  fence_wire_bow: {
    displayName:       'Fence Bow',
    type:              'ranged',
    behavior:          'directional',
    rarity:            'Common',
    atkRange:          360,
    atkDmg:            65,
    atkRate:           0.9,
    bulletCount:       1,
    spread:            0.15,
    projectileSpeed:   580,
    sfxFire:           'shoot',
    sfxFallback:       'shoot',
    sprite:            'fence_wire_bow',
    projectileSprite:  'wire_arrow',
    lootDuration:      null,
    maxProjectiles:    4,
    levels: [
      { atkDmg: 65, atkRate: 0.90, maxProjectiles: 4 },
      { atkDmg: 97.5, atkRate: 0.85, maxProjectiles: 5 },
      { atkDmg: 130, atkRate: 0.80, maxProjectiles: 6 },
      { atkDmg: 162.5, atkRate: 0.75, maxProjectiles: 7 },
      { atkDmg: 195, atkRate: 0.70, maxProjectiles: 8 },
    ],
  },
};

// Returns weapon stats merged with the per-level overrides for slot.level.
// When def.levels is absent (or level 1 baseline), returns the def unchanged.
export function resolveWeaponStats(slot) {
  const def = WEAPON_DEFS[slot?.key];
  if (!def) return {};
  const lvl = def.levels?.[slot.level - 1] ?? {};
  return { key: slot.key, ...def, ...lvl };
}
